# 모델생성과 성능평가 Lab

In [1]:
import numpy as np 
import pandas as pd 
import os

1. customer_scaled.csv 파일을 읽어서 customer_df에 저장하시오. 저장 후에 데이터의 특성을 탐색하시오.

In [2]:
# load data
os.chdir(r'C:\Users\USER\kjw\데이터마이닝개론_24_2\모델생성과성능평가')
customer_df = pd.read_csv('customer_scaled.csv')
customer_df

Gender  MaritalStatus  HomeOwnerFlag  NumberCarsOwned  \
0         0.0            1.0            1.0              0.6   
1         0.0            1.0            1.0              0.4   
2         1.0            0.0            0.0              0.6   
3         0.0            1.0            1.0              0.4   
4         0.0            0.0            1.0              0.2   
...       ...            ...            ...              ...   
18350     1.0            1.0            1.0              0.2   
18351     1.0            0.0            0.0              0.2   
18352     1.0            0.0            0.0              0.0   
18353     1.0            0.0            0.0              0.2   
18354     1.0            1.0            1.0              0.0   

       NumberChildrenAtHome  TotalChildren  YearlyIncome  BikeBuyer  \
0                  0.000000       0.333333      0.496842        1.0   
1                  0.333333       0.666667      0.489453        1.0   
2                  0.000000       0.000000      0.536172        1.0   
3                  0.333333       0.666667      0.317083        1.0   
4                  0.000000       0.000000      0.231958        1.0   
...                     ...            ...           ...        ...   
18350              0.000000       0.666667      0.544379        0.0   
18351              0.000000       0.000000      0.518464        1.0   
18352              0.000000       0.000000      0.224543        1.0   
18353              0.000000       0.000000      0.072511        0.0   
18354              0.333333       0.666667      0.038028        1.0   

       AvgMonthSpend       Age  ...  Education_Bachelors  \
0           0.324210  0.185714  ...                  1.0   
1           0.425201  0.400000  ...                  0.0   
2           0.470977  0.214286  ...                  1.0   
3           0.605474  0.328571  ...                  0.0   
4           0.533742  0.357143  ...                  0.0   
...              ...       ...  ...                  ...   
18350       0.190656  0.571429  ...                  1.0   
18351       0.289287  0.200000  ...                  0.0   
18352       0.257669  0.200000  ...                  0.0   
18353       0.345446  0.242857  ...                  0.0   
18354       0.385559  0.285714  ...                  0.0   

       Education_Graduate Degree  Education_High School  \
0                            0.0                    0.0   
1                            0.0                    0.0   
2                            0.0                    0.0   
3                            0.0                    0.0   
4                            0.0                    0.0   
...                          ...                    ...   
18350                        0.0                    0.0   
18351                        1.0                    0.0   
18352                        1.0                    0.0   
18353                        0.0                    0.0   
18354                        0.0                    0.0   

       Education_Partial College  Education_Partial High School  \
0                            0.0                            0.0   
1                            1.0                            0.0   
2                            0.0                            0.0   
3                            1.0                            0.0   
4                            1.0                            0.0   
...                          ...                            ...   
18350                        0.0                            0.0   
18351                        0.0                            0.0   
18352                        0.0                            0.0   
18353                        0.0                            1.0   
18354                        1.0                            0.0   

       Occupation_Clerical  Occupation_Management  Occupation_Manual  \
0                      1.0                    0.0                0.0   
1     

In [3]:
# shape of dataframe
customer_df.shape

(18355, 26)

In [6]:
# dataframe dtypes for each feature
customer_df.dtypes

Gender                              float64
MaritalStatus                       float64
HomeOwnerFlag                       float64
NumberCarsOwned                     float64
NumberChildrenAtHome                float64
TotalChildren                       float64
YearlyIncome                        float64
BikeBuyer                           float64
AvgMonthSpend                       float64
Age                                 float64
CountryRegionName_Australia         float64
CountryRegionName_Canada            float64
CountryRegionName_France            float64
CountryRegionName_Germany           float64
CountryRegionName_United Kingdom    float64
CountryRegionName_United States     float64
Education_Bachelors                 float64
Education_Graduate Degree           float64
Education_High School               float64
Education_Partial College           float64
Education_Partial High School       float64
Occupation_Clerical                 float64
Occupation_Management           

2. BikeBuyer를 제외한 컬럼으로 입력변수들로, BikeBuyer를 출력변수로 하고, 훈련 데이터와 테스트 데이터를 8:2로 분할하시오.

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(customer_df.drop(['BikeBuyer'],axis=1), customer_df['BikeBuyer'], test_size=0.2, random_state=42)
print('train data set size = {0},  test data set size = {1}'.format(X_train.shape[0],X_test.shape[0]))

train data set size = 14684,  test data set size = 3671


3. 분류 모델의 성능을 출력하는 함수 get_clf_eval()을 작성하시오.

In [5]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score , recall_score, accuracy_score

def get_clf_eval(y_test,pred):
    confusion = confusion_matrix(y_test,pred)
    accuracy = accuracy_score(y_test,pred)
    recall = recall_score(y_test,pred)
    precision = precision_score(y_test,pred)
    print('confusion matrix')
    print(confusion)
    print("정확도: {0:.4f}. 재현율: {0:.4f}, 정밀도: {0:.4f}".format(accuracy, recall, precision))

4. 의사결정나무를 만들고 분류 성능을 평가하시오.

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
# Decision Tree Classifer
dt_clf=DecisionTreeClassifier(random_state=123)
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=123)

In [18]:
dt_pred = dt_clf.predict(X_test)

In [19]:
get_clf_eval(y_test,dt_pred)

confusion matrix
[[ 813  862]
 [ 860 1136]]
정확도: 0.5309. 재현율: 0.5309, 정밀도: 0.5309


5. 로지스틱 회귀 분석 모형을 만들고 분류 성능을 평가하시오.

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
lr_clf = LogisticRegression()
lr_clf.fit(X_train, y_train)
lr_pred = lr_clf.predict(X_test)

In [22]:
get_clf_eval(y_test,lr_pred)

confusion matrix
[[ 831  844]
 [ 544 1452]]
정확도: 0.6219. 재현율: 0.6219, 정밀도: 0.6219


6. 랜덤포레스트 모형을 만들고 분류 성능을 평가하시오.

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train , y_train)
rf_pred = rf_clf.predict(X_test)

In [25]:
get_clf_eval(y_test,rf_pred)

confusion matrix
[[ 793  882]
 [ 556 1440]]
정확도: 0.6083. 재현율: 0.6083, 정밀도: 0.6083


7. MLP 모형을 만들고 분류 성능을 평가하시오(단 히든 레이어는 (8,8)로 하시오).

In [6]:
from sklearn.neural_network import MLPClassifier

In [7]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(8,8), max_iter=300)
mlp_clf.fit(X_train , y_train)
mlp_pred = mlp_clf.predict(X_test)

In [8]:
get_clf_eval(y_test,mlp_pred)

confusion matrix
[[ 681  994]
 [ 401 1595]]
정확도: 0.6200. 재현율: 0.6200, 정밀도: 0.6200
