# Numpy ndarray 개요

## np.array(list)
list를 받아 numpy.ndarray 반환 (타입을 변환함)

```python
# 선언
array1 = np.array([1,2,'hello?'])

# array.shape: (행, 열)을 출력
array1.shape

# array.ndim: 차원을 출력
array.ndim

# array.dtype: 원소의 데이터타입을 출력
## array의 원소들은 하나의 타입으로 통일됨
array.dtype
```


In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3]) # numpy.ndarray 객체 생성
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape) # shape -> (행, 열)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [3]:
array2 = np.array([[1,2,3],
                  [2,3,4]]) # 행 2개, 열 3개인 array 생성
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [4]:
array3 = np.array([[1,2,3]]) # 행 1개, 열 3개
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))


array1: 1차원, array2: 2차원, array3:  2차원


### .dtype : 원소들의 데이터타입을 반환
단, numpy에서는 upcasting(하나의 통일된 타입을 반환)이 적용됨
```
부울형 (boolean) → 정수형 (integer)
부울형 True/False는 정수형으로 변환될 때, True는 1, False는 0으로 변환됩니다.

정수형 (integer) → 실수형 (floating-point)
정수형이 실수형과 함께 있으면, 정수형이 실수형으로 변환됩니다.

실수형 (float) → 복소수형 (complex)
실수형과 복소수형이 함께 있으면, 실수형이 복소수형으로 변환됩니다.

숫자형 (number) → 문자열형 (string)
만약 숫자와 문자열이 혼합되어 있으면, 숫자들이 문자열로 변환됩니다.
```

### .astype('type')
타입을 직접 캐스팅함
```
array_float = array_int.astype('float64')
```

In [ ]:
list1 = [1,2,3]
print(type(list1)) # python list
array1 = np.array(list1)
print(type(array1)) # numpy.ndarray
print(array1, array1.dtype) ## array.dtype: element's data type
## 넘파이에서는 모든 원소들이 같은 타입을 가져야함

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [6]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U21


In [7]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [8]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [9]:
array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [10]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


## ndarray를 편리하게 생성하기 - arange, zeros, ones

```python
# np.arrange(start=0, end required, step=1)
## .range 함수와 유사
np.arrange(10)

# np.zeros(rows, columns) / np.zeros(shape, dtype, order)
## 원소가 0인 리스트를 반환
np.zeros(3, 2)

# [[0 0]
#  [0 0]
#  [0 0]]

# np.ones(rows, columns) / np.ones(shape, dtype, order)
np.ones(3, 2)

# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]

```



In [11]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [12]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [13]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## reshape

```python
# array.reshape(rows, columns)
array_reshaped = array.reshape(2, 5)

## 만약, 원소의 개수와 매치되지 않는다면, 에러를 반환
## reshape(음수/양수)
하나의 차원에서만 사용가능
array_reshaped = array.reshape(-1, 4) # 음수 부분을 자동으로 채워줌

```


In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [ ]:
array2 = array1.reshape(2,5)
print('array2:\n',array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
array3 = array1.reshape(5,2)
print('array3:\n',array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# 에러발생: 요소(element) 수가 shape을 만족시키지 못할 때
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)


In [ ]:
array3 = array1.reshape(5,-1) # 음수 부분은 알아서 채워짐
print('array3 shape:',array3.shape)

array3 shape: (5, 2)


In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) # 어떠한 수로도 채울 수 없는 경우 에러발생

ValueError: cannot reshape array of size 10 into shape (4)

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## indexing
```python
# array[index]
array[0]
2darray[row, col]
```

* 단일값 추출

In [ ]:
# 1에서 부터 9 까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [ ]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


## Slicing
```python
# array1d (1차원)
array1d[start_index : end_index+1]

# array2d (2차원)
array2d[row_slicing, column_slicing]

```



In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### fancy indexing

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* Boolean indexing

In [ ]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]
